main: com.cavetale.poster.PosterPlugin

version: 0.1
api-version: '1.21.10'

name: Poster
description: Make map walls from image files

author: StarTux
website: https://github.com/StarTux/Poster

depend: [Core]
softdepend: []

commands:

  poster:
    aliases: []
    description: Poster Command
    permission: poster.poster
    usage: |-
      /poster

permissions:

  poster.poster:
    description: Use /poster
    default: op
